%% Sequence diagram code
sequenceDiagram
    UA1 ->> Proxy1: Request
    Note right of Proxy1: OK, Request foward to Proxy2
    Proxy1 -->> Proxy2: Request
    activate Proxy1
    Note right of Proxy1: 1. Make a copy request
    Note right of Proxy1: 2. Update Request-URI, Max-Forwards
    Note right of Proxy1: 3. Add header fields(Record-route)
    Note right of Proxy1: 4. Postprocess routing informaiton
    Note right of Proxy1: 5. Determine next-hop ip,port,tr
    Note right of Proxy1: 6. Add Via, Content-Length
    Note right of Proxy1: 7. Forward ---> 
    Note right of Proxy1: 8. Set timer C
    deactivate Proxy1
    Proxy2 ->> UA2: Request
