%% Sequence diagram code
sequenceDiagram
    UA1 ->> Proxy1: Request
    Proxy1 ->> Proxy2: Request
    activate Proxy1
    Note right of Proxy1: 1. Request-URI 확인
    Note right of Proxy1: 2. Route header 가장 위에 있는 URI 확인
    Note right of Proxy1: 3. address, port, transport 결정
    deactivate Proxy1
    Proxy2 ->> UA2: Request
    UA2 -x Proxy2: Response
    Proxy2 -x Proxy1: Response
    Proxy1 -x UA1: Response
